infisical:
  # Otherwise, the default is `infisical-infisical-standalone`
  fullnameOverride: infisical
  image:
    repository: infisical/infisical
    tag: "v0.101.3-postgres"
    pullPolicy: IfNotPresent
postgresql:
  enabled: true
redis:
  enabled: true
ingress:
  enabled: true
  nginx:
    enabled: false
